In [ ]:
/content/drive/MyDrive/Colab Notebooks/WEEK02/diabetes.csv

In [ ]:
# diabetes.csv 파일을 바탕으로 LR, DT, RF classification 실습

import pandas as pd
import numpy as np

path = '/content/drive/MyDrive/Colab Notebooks/WEEK02/diabetes.csv'

# DataFrame으로 읽기
df = pd.read_csv(path)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
y = df['Outcome']
y.value_counts()
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [ ]:
X = df.drop('Outcome', axis=1)
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)

In [ ]:
# LR
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_lr = LogisticRegression(random_state=0, max_iter=1000)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print("\n--- Logistic Regression Classifier ---")
print("정확도 :", accuracy_score(y_test, pred_lr))
print("혼동행렬 :")
print(confusion_matrix(y_test, pred_lr))

--- Logistic Regression Classifier ---
정확도 : 0.796875
혼동행렬 :
[[117  13]
 [ 26  36]]

In [ ]:
# DT
from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print("\n--- Decision Tree Classifier ---")
print("정확도 :", accuracy_score(y_test, pred_dt))
print("혼동행렬 :")
print(confusion_matrix(y_test, pred_dt))

--- Decision Tree Classifier ---
정확도 : 0.71875
혼동행렬 :
[[102  28]
 [ 26  36]]

In [ ]:
# RF
from sklearn.ensemble import RandomForestClassifier

clf_rf = RandomForestClassifier(random_state=0)
clf_rf.fit(X_train, y_train)

pred_rf = clf_rf.predict(X_test)

print("\n--- Random Forest Classifier ---")
print("정확도 :", accuracy_score(y_test, pred_rf))
print("혼동행렬 :")
print(confusion_matrix(y_test, pred_rf))

--- Random Forest Classifier ---
정확도 : 0.7708333333333334
혼동행렬 :
[[116  14]
 [ 30  32]]